export const vpcEnv = 'vpc-064b53adf53b4f4fc'
export const PGHOST = 'connection-testing.cpxps3qi8vjy.us-east-2.rds.amazonaws.com'
export const PGUSER = 'bmeneses'
export const PGDATABASE = 'postgres'
export const PGPASSWORD = 'Jejexdlol123'